version: '3.2'
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/mysql/datadir:/var/lib/mysql
    networks:
      - internal
    ports:
      - ${DB_PORT}:3306
  front:
    build:
      context: ./docker/nginx
    ports:
      - ${FRONTS_PORT}:80
    volumes:
      - ./:/var/www
    depends_on:
      - backend
    networks:
      - internal
  backend: #&app
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: db
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - internal
networks:
  internal:
    driver: bridge